# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(513, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(513, 666))
        MainWindow.setMaximumSize(QtCore.QSize(513, 666))
        MainWindow.setTabletTracking(False)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setBaseSize(QtCore.QSize(480, 590))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 840, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_setting)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 10, 131, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cc2640_comboBox_port = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cc2640_comboBox_port.setObjectName("cc2640_comboBox_port")
        self.verticalLayout.addWidget(self.cc2640_comboBox_port)
        self.cc2640_comboBox_baudrate = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cc2640_comboBox_baudrate.setObjectName("cc2640_comboBox_baudrate")
        self.verticalLayout.addWidget(self.cc2640_comboBox_baudrate)
        self.cc2640_comboBox_databits = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cc2640_comboBox_databits.setObjectName("cc2640_comboBox_databits")
        self.verticalLayout.addWidget(self.cc2640_comboBox_databits)
        self.cc2640_comboBox_parity = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cc2640_comboBox_parity.setObjectName("cc2640_comboBox_parity")
        self.verticalLayout.addWidget(self.cc2640_comboBox_parity)
        self.cc2640_comboBox_Stopbits = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cc2640_comboBox_Stopbits.setObjectName("cc2640_comboBox_Stopbits")
        self.verticalLayout.addWidget(self.cc2640_comboBox_Stopbits)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_setting)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 10, 111, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.line = QtWidgets.QFrame(self.tab_setting)
        self.line.setGeometry(QtCore.QRect(0, 190, 991, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_setting)
        self.line_2.setGeometry(QtCore.QRect(-10, 370, 1001, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton.setGeometry(QtCore.QRect(340, 170, 131, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 170, 111, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.csm3510_comboBox_port = QtWidgets.QComboBox(self.tab_setting)
        self.csm3510_comboBox_port.setGeometry(QtCore.QRect(340, 210, 131, 21))
        self.csm3510_comboBox_port.setObjectName("csm3510_comboBox_port")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_setting)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(340, 390, 131, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.current_comboBox_port = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.current_comboBox_port.setObjectName("current_comboBox_port")
        self.verticalLayout_3.addWidget(self.current_comboBox_port)
        self.current_comboBox_baudrate = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.current_comboBox_baudrate.setObjectName("current_comboBox_baudrate")
        self.verticalLayout_3.addWidget(self.current_comboBox_baudrate)
        self.current_comboBox_databits = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.current_comboBox_databits.setObjectName("current_comboBox_databits")
        self.verticalLayout_3.addWidget(self.current_comboBox_databits)
        self.current_comboBox_parity = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.current_comboBox_parity.setObjectName("current_comboBox_parity")
        self.verticalLayout_3.addWidget(self.current_comboBox_parity)
        self.current_comboBox_stopbIts = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.current_comboBox_stopbIts.setObjectName("current_comboBox_stopbIts")
        self.verticalLayout_3.addWidget(self.current_comboBox_stopbIts)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_setting)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(220, 390, 111, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_4.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_4.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_4.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_4.addWidget(self.lineEdit_10)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 840, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 260, 111, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_setting)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 191, 161))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_setting)
        self.graphicsView_2.setEnabled(True)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 230, 191, 51))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_setting)
        self.graphicsView_3.setEnabled(True)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 410, 191, 161))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(220, 210, 109, 20))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 550, 131, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 550, 111, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_8.setGeometry(QtCore.QRect(340, 260, 131, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 390, 191, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 210, 191, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 10, 191, 20))
        self.lineEdit_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.line_3 = QtWidgets.QFrame(self.tab_setting)
        self.line_3.setGeometry(QtCore.QRect(0, 280, 491, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 350, 111, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_setting)
        self.graphicsView_4.setEnabled(True)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 320, 191, 51))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_setting)
        self.pushButton_10.setGeometry(QtCore.QRect(340, 350, 131, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_15.setEnabled(False)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 300, 191, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.printer_comboBox_port = QtWidgets.QComboBox(self.tab_setting)
        self.printer_comboBox_port.setGeometry(QtCore.QRect(340, 300, 131, 21))
        self.printer_comboBox_port.setObjectName("printer_comboBox_port")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_setting)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setGeometry(QtCore.QRect(220, 300, 109, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.tabWidget.addTab(self.tab_setting, "")
        self.tab_tracking = QtWidgets.QWidget()
        self.tab_tracking.setObjectName("tab_tracking")
        self.tabWidget.addTab(self.tab_tracking, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_log)
        self.plainTextEdit.setGeometry(QtCore.QRect(5, 1, 481, 571))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget.addTab(self.tab_log, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 23))
        self.menubar.setObjectName("menubar")
        self.menuhello = QtWidgets.QMenu(self.menubar)
        self.menuhello.setObjectName("menuhello")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionautoDetect = QtWidgets.QAction(MainWindow)
        self.actionautoDetect.setObjectName("actionautoDetect")
        self.menuhello.addSeparator()
        self.menuhello.addAction(self.actionautoDetect)
        self.menuhello.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionVersion)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuhello.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSM3510_Helper"))
        self.pushButton_3.setText(_translate("MainWindow", "开始"))
        self.lineEdit_3.setText(_translate("MainWindow", "    端    口"))
        self.lineEdit_2.setText(_translate("MainWindow", "    波 特 率"))
        self.lineEdit.setText(_translate("MainWindow", "    数 据 位"))
        self.lineEdit_5.setText(_translate("MainWindow", "    校 验 位"))
        self.lineEdit_4.setText(_translate("MainWindow", "    停 止 位"))
        self.pushButton.setText(_translate("MainWindow", "停    止"))
        self.pushButton_2.setText(_translate("MainWindow", "开    始"))
        self.lineEdit_6.setText(_translate("MainWindow", "    端    口"))
        self.lineEdit_7.setText(_translate("MainWindow", "    波 特 率"))
        self.lineEdit_8.setText(_translate("MainWindow", "    数 据 位"))
        self.lineEdit_9.setText(_translate("MainWindow", "    校 验 位"))
        self.lineEdit_10.setText(_translate("MainWindow", "    停 止 位"))
        self.pushButton_4.setText(_translate("MainWindow", "停止"))
        self.pushButton_5.setText(_translate("MainWindow", "开    始"))
        self.lineEdit_11.setText(_translate("MainWindow", "     CSM3510"))
        self.pushButton_6.setText(_translate("MainWindow", "停    止"))
        self.pushButton_7.setText(_translate("MainWindow", "确    认"))
        self.pushButton_8.setText(_translate("MainWindow", "停    止"))
        self.lineEdit_12.setText(_translate("MainWindow", "配置电流表串口"))
        self.lineEdit_13.setText(_translate("MainWindow", "配置CSM3510串口"))
        self.lineEdit_14.setText(_translate("MainWindow", "配置测试架串口"))
        self.pushButton_9.setText(_translate("MainWindow", "确    认"))
        self.pushButton_10.setText(_translate("MainWindow", "重    选"))
        self.lineEdit_15.setText(_translate("MainWindow", "配置打印机"))
        self.lineEdit_16.setText(_translate("MainWindow", "    打 印 机"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), _translate("MainWindow", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tracking), _translate("MainWindow", "跟踪"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("MainWindow", "日志"))
        self.menuhello.setTitle(_translate("MainWindow", "设置"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionVersion.setText(_translate("MainWindow", "版本号"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionAbout.setIconText(_translate("MainWindow", "关于"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionautoDetect.setText(_translate("MainWindow", "自动配置"))

